//! Structured event log types for `notebook.git/.trust/events.yml`.
//!
//! The event log is the canonical source of trust state. The three
//! OpenSSH-format files (`historical_signers`, `allowed_signers`,
//! `revoked_signers`) are derived projections regenerated by
//! `trust::regenerate_files`.

use std::path::Path;

use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Top-level `events.yml` document.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EventLog {
    pub schema_version: u32,
    pub events: Vec<Event>,
}

/// A single trust event with a stable `UUIDv7` identity.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Event {
    pub event_id: Uuid,
    #[serde(flatten)]
    pub payload: EventKind,
}

/// All possible trust event kinds (events.yml shape).
///
/// Serialized with `#[serde(tag = "kind")]` so the YAML includes `kind: BootstrapKey` etc.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum EventKind {
    /// Initial bootstrap event written by `nexum init`. Chain root.
    BootstrapKey {
        fingerprint: String,
        public_key: String,
        reason: String,
    },
    /// A new key was added by `nexum keys add`.
    KeyAdded {
        fingerprint: String,
        public_key: String,
        reason: String,
    },
    /// A key was routinely retired (records signed by it remain valid).
    KeyRotatedOut { fingerprint: String, reason: String },
    /// A key was marked as compromised (records carry warning under default;
    /// filtered under `--strict-revocation`).
    KeyCompromised { fingerprint: String, reason: String },
    /// Chain break: bootstrap key lost, user-acknowledged reanchor.
    BootstrapReanchor {
        old_fingerprint: String,
        new_fingerprint: String,
        reason: String,
    },
}

impl EventKind {
    /// String form used in the `trust_events.kind` SQL column. Matches
    /// the schema's `CHECK` constraint and the `#[serde(tag = "kind")]`
    /// discriminator used in `events.yml`.
    pub(crate) fn as_db_str(&self) -> &'static str {
        match self {
            EventKind::BootstrapKey { .. } => "BootstrapKey",
            EventKind::KeyAdded { .. } => "KeyAdded",
            EventKind::KeyRotatedOut { .. } => "KeyRotatedOut",
            EventKind::KeyCompromised { .. } => "KeyCompromised",
            EventKind::BootstrapReanchor { .. } => "BootstrapReanchor",
        }
    }
}

#[derive(Debug, thiserror::Error)]
pub enum TrustError {
    /// Filesystem error.
    #[error("trust I/O error at {path}: {source}")]
    Io {
        path: String,
        #[source]
        source: std::io::Error,
    },
    /// YAML parse error.
    #[error("trust YAML parse error in {path}: {source}")]
    Parse {
        path: String,
        #[source]
        source: serde_yaml::Error,
    },
    /// YAML serialization error.
    #[error("trust YAML serialize error: {0}")]
    Serialize(serde_yaml::Error),
    /// `config.toml` parse error encountered when reading `[trust.bootstrap]`.
    #[error("config.toml parse error in {path}: {cause}")]
    ConfigParse { path: String, cause: String },
    /// `[trust.bootstrap]` section missing from `config.toml`.
    #[error("bootstrap pin missing from config.toml")]
    BootstrapPinMissing,
    /// `~/.nexum/.reanchor_pending` sentinel detected; commands must refuse.
    #[error("reanchor pending: {message}")]
    ReanchorPending { message: String },
    /// Underlying `git` command exited non-zero during the events.yml history walk.
    #[error("git command failed: {stderr}")]
    GitCommand { stderr: String },
    /// `.trust/events.yml` history contains merge commits; the materializer
    /// only supports a linear chain.
    #[error(".trust/events.yml has merge commits in its history (linear history is required)")]
    TrustHistoryNotLinear,
    /// `events.yml` declares a `schema_version` this binary does not support.
    #[error("trust schema v{found} unsupported by this binary")]
    TrustSchemaUnsupported { found: u32 },
    /// First `events.yml` revision is not exactly one `BootstrapKey` event.
    #[error("first events.yml revision must contain exactly one BootstrapKey event")]
    MalformedBootstrap,
    /// Sqlite error during materialization.
    #[error("sqlite error during trust materialization: {0}")]
    Sqlite(#[from] rusqlite::Error),
}

/// Write the seed `events.yml` for `nexum init`.
///
/// Creates a single-event log with the `BootstrapKey` event.
///
/// # Errors
///
/// Returns `TrustError::Serialize` on YAML serialization failure.
/// Returns `TrustError::Io` on write failure.
pub fn write_seed_yaml(
    path: &Path,
    bootstrap_fingerprint: &str,
    bootstrap_public_key: &str,
) -> Result<EventLog, TrustError> {
    let log = EventLog {
        schema_version: 1,
        events: vec![Event {
            event_id: Uuid::now_v7(),
            payload: EventKind::BootstrapKey {
                fingerprint: bootstrap_fingerprint.to_owned(),
                public_key: bootstrap_public_key.to_owned(),
                reason: "Initial bootstrap".to_owned(),
            },
        }],
    };
    let yaml = serde_yaml::to_string(&log).map_err(TrustError::Serialize)?;
    std::fs::write(path, yaml).map_err(|e| TrustError::Io {
        path: path.display().to_string(),
        source: e,
    })?;
    Ok(log)
}

/// Read and parse `events.yml` from `path`.
///
/// # Errors
///
/// Returns `TrustError::Io` on read failure, `TrustError::Parse` on YAML parse failure.
pub fn load_events_yml(path: &Path) -> Result<EventLog, TrustError> {
    let raw = std::fs::read_to_string(path).map_err(|e| TrustError::Io {
        path: path.display().to_string(),
        source: e,
    })?;
    serde_yaml::from_str(&raw).map_err(|e| TrustError::Parse {
        path: path.display().to_string(),
        source: e,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn fake_fingerprint() -> String {
        "SHA256:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=".to_owned()
    }

    fn fake_pubkey() -> String {
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFakeKeyForTesting test@example.invalid".to_owned()
    }

    #[test]
    fn write_and_load_seed_round_trips() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("events.yml");
        let log = write_seed_yaml(&path, &fake_fingerprint(), &fake_pubkey()).unwrap();
        let loaded = load_events_yml(&path).unwrap();
        assert_eq!(log, loaded);
    }

    #[test]
    fn seed_has_schema_version_one() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("events.yml");
        let log = write_seed_yaml(&path, &fake_fingerprint(), &fake_pubkey()).unwrap();
        assert_eq!(log.schema_version, 1);
    }

    #[test]
    fn seed_has_exactly_one_bootstrap_key_event() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("events.yml");
        let log = write_seed_yaml(&path, &fake_fingerprint(), &fake_pubkey()).unwrap();
        assert_eq!(log.events.len(), 1);
        assert!(matches!(
            log.events[0].payload,
            EventKind::BootstrapKey { .. }
        ));
    }

    #[test]
    fn bootstrap_event_carries_fingerprint() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("events.yml");
        let fp = fake_fingerprint();
        let log = write_seed_yaml(&path, &fp, &fake_pubkey()).unwrap();
        let EventKind::BootstrapKey { fingerprint, .. } = &log.events[0].payload else {
            panic!("expected BootstrapKey");
        };
        assert_eq!(fingerprint, &fp);
    }

    #[test]
    fn all_five_event_kinds_round_trip_yaml() {
        let events = vec![
            EventKind::BootstrapKey {
                fingerprint: fake_fingerprint(),
                public_key: fake_pubkey(),
                reason: "Initial bootstrap".into(),
            },
            EventKind::KeyAdded {
                fingerprint: "SHA256:BBB=".into(),
                public_key: "ssh-ed25519 BBBB test2@example.invalid".into(),
                reason: "Second key".into(),
            },
            EventKind::KeyRotatedOut {
                fingerprint: fake_fingerprint(),
                reason: "Routine rotation".into(),
            },
            EventKind::KeyCompromised {
                fingerprint: "SHA256:BBB=".into(),
                reason: "Suspected leak".into(),
            },
            EventKind::BootstrapReanchor {
                old_fingerprint: fake_fingerprint(),
                new_fingerprint: "SHA256:CCC=".into(),
                reason: "Bootstrap key lost".into(),
            },
        ];
        for (i, kind) in events.into_iter().enumerate() {
            let log = EventLog {
                schema_version: 1,
                events: vec![Event {
                    event_id: Uuid::now_v7(),
                    payload: kind,
                }],
            };
            let yaml = serde_yaml::to_string(&log).unwrap_or_else(|e| panic!("event {i}: {e}"));
            let back: EventLog =
                serde_yaml::from_str(&yaml).unwrap_or_else(|e| panic!("event {i} parse: {e}"));
            assert_eq!(log, back, "event {i} round-trip failed");
        }
    }
}
